Coupon.create(coupon_code: "83kakjdfkj91", store: "Target")
Coupon.create(coupon_code: "aldjfakldjf887", store: "Chipotle")
Coupon.create(coupon_code: "8347aldkjff1", store: "Barnes & Noble")
Coupon.create(coupon_code: "84749fjdjf", store: "Whole Foods")
Coupon.create(coupon_code: "8373000dfj", store: "Hermes")
